"use client";

import { motion } from "framer-motion";
import { Download, TrendingUp, TrendingDown, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FinalReport } from "@/lib/ai-mrv/reportGenerator";
import { toast } from "sonner";

interface QualityReportCardProps {
  report: FinalReport;
}

export function QualityReportCard({ report }: QualityReportCardProps) {
  const getScoreColor = (score: number) => {
    if (score >= 85) return "text-carbon-green-400";
    if (score >= 70) return "text-blue-400";
    if (score >= 50) return "text-yellow-400";
    return "text-red-400";
  };

  const getScoreLabel = (score: number) => {
    if (score >= 85) return "Excellent";
    if (score >= 70) return "Good";
    if (score >= 50) return "Moderate";
    return "Needs Improvement";
  };

  const handleDownload = () => {
    // Create a simple text report
    const reportText = `
CARBON PROJECT QUALITY REPORT
==============================

Overall Quality Score: ${report.qualityScore}/100
Rating: ${getScoreLabel(report.qualityScore)}

SUMMARY
-------
${report.summary}

STRENGTHS
---------
${report.strengths.map((s, i) => `${i + 1}. ${s}`).join("\n")}

WEAKNESSES
----------
${report.weaknesses.map((w, i) => `${i + 1}. ${w}`).join("\n")}

RECOMMENDATIONS
---------------
${report.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

Generated by Carbon Trade X AI MRV System
    `.trim();

    // Create blob and download
    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `carbon-quality-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Report downloaded successfully");
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.3 }}
    >
      <Card className="border-carbon-green-700 bg-gradient-to-br from-carbon-green-950/50 to-gray-900">
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <CardTitle className="text-2xl mb-2">
                Quality Assessment Report
              </CardTitle>
              <CardDescription>
                Comprehensive analysis by AI MRV multi-agent system
              </CardDescription>
            </div>
            <Button onClick={handleDownload} variant="outline" size="sm">
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
          </div>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Quality Score */}
          <div className="text-center p-6 rounded-lg bg-gray-900/50 border border-gray-800">
            <p className="text-sm text-gray-400 mb-2">Overall Quality Score</p>
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: "spring", stiffness: 200, delay: 0.2 }}
              className={`text-6xl font-bold ${getScoreColor(report.qualityScore)} mb-2`}
            >
              {report.qualityScore}
              <span className="text-3xl">/100</span>
            </motion.div>
            <Badge
              variant="outline"
              className={`${getScoreColor(report.qualityScore)} border-current`}
            >
              {getScoreLabel(report.qualityScore)}
            </Badge>
          </div>

          {/* Summary */}
          <div>
            <h3 className="text-lg font-semibold text-gray-200 mb-2">
              Summary
            </h3>
            <p className="text-gray-400 leading-relaxed">{report.summary}</p>
          </div>

          {/* Strengths */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <TrendingUp className="w-5 h-5 text-carbon-green-400" />
              <h3 className="text-lg font-semibold text-gray-200">Strengths</h3>
            </div>
            <ul className="space-y-2">
              {report.strengths.map((strength, index) => (
                <motion.li
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="flex items-start gap-2 text-gray-300"
                >
                  <span className="text-carbon-green-400 mt-1">✓</span>
                  <span>{strength}</span>
                </motion.li>
              ))}
            </ul>
          </div>

          {/* Weaknesses */}
          {report.weaknesses.length > 0 && (
            <div>
              <div className="flex items-center gap-2 mb-3">
                <TrendingDown className="w-5 h-5 text-yellow-400" />
                <h3 className="text-lg font-semibold text-gray-200">
                  Areas for Improvement
                </h3>
              </div>
              <ul className="space-y-2">
                {report.weaknesses.map((weakness, index) => (
                  <motion.li
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="flex items-start gap-2 text-gray-300"
                  >
                    <span className="text-yellow-400 mt-1">!</span>
                    <span>{weakness}</span>
                  </motion.li>
                ))}
              </ul>
            </div>
          )}

          {/* Recommendations */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <AlertCircle className="w-5 h-5 text-blue-400" />
              <h3 className="text-lg font-semibold text-gray-200">
                Recommendations
              </h3>
            </div>
            <ul className="space-y-2">
              {report.recommendations.map((recommendation, index) => (
                <motion.li
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="flex items-start gap-2 text-gray-300"
                >
                  <span className="text-blue-400 mt-1">→</span>
                  <span>{recommendation}</span>
                </motion.li>
              ))}
            </ul>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}
